name: GHA-PR-test2

on:
  pull_request:
    types: ready_for_review
    branches:
      - master

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Use cancel redundant
        uses: technote-space/auto-cancel-redundant-job@v1

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Run job
        run: ./myscript.sh
